-- MySQL Script generated by MySQL Workbench
-- Mon May 16 16:10:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd_film
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_film
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_film` DEFAULT CHARACTER SET utf8mb4 ;
USE `bdd_film` ;

-- -----------------------------------------------------
-- Table `bdd_film`.`Annee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_film`.`Annee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_film`.`Nom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_film`.`Nom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_film` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL,
  `Category_id` INT NOT NULL,
  `Annee_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Category_id`, `Annee_id`),
  INDEX `fk_Nom_Annee1_idx` (`Annee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Nom_Annee1`
    FOREIGN KEY (`Annee_id`)
    REFERENCES `bdd_film`.`Annee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_film`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_film`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_nom` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_film`.`Realisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_film`.`Realisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `realisateur_nom` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_film`.`Nom_has_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_film`.`Nom_has_Category` (
  `Nom_id` INT NOT NULL,
  `Nom_Category_id` INT NOT NULL,
  `Nom_Annee_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`Nom_id`, `Nom_Category_id`, `Nom_Annee_id`, `Category_id`),
  INDEX `fk_Nom_has_Category_Category1_idx` (`Category_id` ASC) VISIBLE,
  INDEX `fk_Nom_has_Category_Nom1_idx` (`Nom_id` ASC, `Nom_Category_id` ASC, `Nom_Annee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Nom_has_Category_Nom1`
    FOREIGN KEY (`Nom_id` , `Nom_Category_id` , `Nom_Annee_id`)
    REFERENCES `bdd_film`.`Nom` (`id` , `Category_id` , `Annee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nom_has_Category_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `bdd_film`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_film`.`Nom_has_Realisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_film`.`Nom_has_Realisateur` (
  `Nom_id` INT NOT NULL,
  `Nom_Category_id` INT NOT NULL,
  `Nom_Annee_id` INT NOT NULL,
  `Realisateur_id` INT NOT NULL,
  PRIMARY KEY (`Nom_id`, `Nom_Category_id`, `Nom_Annee_id`, `Realisateur_id`),
  INDEX `fk_Nom_has_Realisateur_Realisateur1_idx` (`Realisateur_id` ASC) VISIBLE,
  INDEX `fk_Nom_has_Realisateur_Nom1_idx` (`Nom_id` ASC, `Nom_Category_id` ASC, `Nom_Annee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Nom_has_Realisateur_Nom1`
    FOREIGN KEY (`Nom_id` , `Nom_Category_id` , `Nom_Annee_id`)
    REFERENCES `bdd_film`.`Nom` (`id` , `Category_id` , `Annee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nom_has_Realisateur_Realisateur1`
    FOREIGN KEY (`Realisateur_id`)
    REFERENCES `bdd_film`.`Realisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
